# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_deps = <<-'SHELL'
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider "virtualbox" do |vb|

    vb.memory = "4096"
    vb.cpus = 2
  end
  config.vm.network "private_network", ip: "192.168.100.100"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  # config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.provision "shell", inline: $install_deps
  config.trigger.after :up do |trigger|
    trigger.info = "Starting Java application..."
    trigger.run_remote = { inline: "cd /vagrant && ./gradlew bootRun" }
  end
end