Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"

  # Web Server VM
  config.vm.define "web" do |web|
    web.vm.hostname = "web-server"
    web.vm.network "public_network", bridge: "wlp58s0", ip: "192.168.50.220"
    web.vm.network "forwarded_port", guest: 80, host: 8081
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
  end

  # Database Server VM
  config.vm.define "db" do |db|
    db.vm.hostname = "db-server"
    db.vm.network "public_network", bridge: "wlp58s0", ip: "192.168.50.221"
    db.vm.network "forwarded_port", guest: 3306, host: 3306
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
  end
end
