pipeline {
    agent any

    stages {
        stage('Prepare') {
            steps {
                sh '''
                curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
                sudo apt-get install -y nodejs
                node -v
                '''
            }
        }

        stage('Build') {
            steps {
                sh 'npm -v'
            }
        }

        stage('Test') {
            steps {
                sh 'echo $JENKINS_URL'
            }
        }
    }
}
