name: Flask API Workflow

on:
  pull_request:
    types: [opened, synchronize]  
  push:
    branches:
      - main
  workflow_dispatch:  
    
jobs:
  flask-pipeline:
    runs-on: ubuntu-latest

    steps:

      # Clone this repo
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Verify contents
        run: ls -la

      # Python
      - name: Setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.12'

      # Requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Database
      - name: Create a database
        run: python db.py

      - name: Verify creation
        run: ls -l products.db
      
      # Database setup
      - name: Delete all product data
        run: python db.py -d

      - name: Add default product data
        run: python db.py -a

      - name:  Print product data to the console
        run: python db.py -p

      # API
      - name: Run the API
        run: python app.py --host localhost --port 5000 &

      - name: Wait for start
        run: sleep 5
        
      # Verify by curl
      - name: Test GET /api/products
        run: |
          curl -X GET http://localhost:5000/api/products

      - name: Test POST /api/products
        run: |
          curl -X POST http://localhost:5000/api/products -H "Content-Type: application/json" -d '{"name": "Avocado", "price": 58}'   

      - name: Test GET /api/products/{product_id}
        run: |
          curl -X GET http://localhost:5000/api/products/3

      - name: Test PATCH /api/products/{product_id}
        run: |
          curl -X PATCH http://localhost:5000/api/products/5 -H "Content-Type: application/json" -d '{"price": 67}'

      - name: Test DELETE /api/products/{product_id}
        run: |
          curl -X DELETE http://localhost:5000/api/products/1

      # Reset DB
      - name: Reset database
        run: |
          python db.py -d
          python db.py
        
      # Unit tests
      - name: Run unit tests
        run: pytest test_app.py
