# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"
  config.vm.hostname = "test"
  config.vm.network "private_network", ip: "192.168.50.50"

  config.vm.provision "shell", inline: <<-SHELL

    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt-get update
    sudo apt-get install python3.12
    python3 --version

    sudo apt install -y python3-pip 
    pip3 --version

    pip install -r requirements.txt --break-system-packages

    python3 db.py
    python3 db.py -d

    pytest test_app.py
  SHELL

end