pipeline {
    agent any

    tools {
        nodejs 'Node22'
    }

    stages {
        stage('Prepare') {
            steps {
                echo '🔧 Встановлюємо Node.js 22...'
                sh 'node -v'
            }
        }

        stage('Build') {
            steps {
                echo '🏗️ Симуляція процесу збирання...'
                sh 'npm -v'
            }
        }

        stage('Test') {
            steps {
                echo '🧪 Симуляція тестування...'
                sh 'echo JENKINS_URL = $JENKINS_URL'
            }
        }
    }
}

