name: Java Maven Wrapper CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3

    - name: Установка прав на mvnw
      run: chmod +x mvnw

    - name: Установка JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Сборка проекта
      run: ./mvnw clean package
