name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set execute permission for Maven wrapper
        run: chmod +x ./mvnw

      - name: Build project
        run: ./mvnw clean package

      - name: Run unit tests
        run: ./mvnw test

      - name: Verify build artifact
        run: ls -l target/*.jar

      - name: Commit changes if any
        run: |
          git config --global user.name 'zinchenko-ihor'
          git config --global user.email 'zinchenkoihor757@gmail.com'
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m 'Automated changes from CI pipeline'
          git push
