# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # C O M M O N   S E T T I N G S
  config.vm.box = "oraclelinux/9"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json"

  config.vm.provision "shell", name: "common", inline: <<-SHELL
    # Disable SELinux permanently
    sudo setenforce 0
    sudo sed -i 's/^SELINUX=enforcing$/SELINUX=disabled/' /etc/selinux/config

    # Install Nginx
    sudo dnf install -y epel-release
    sudo dnf install -y nginx
    sudo systemctl enable --now nginx

    # Install Node.js
    sudo dnf install -y nodejs npm
  SHELL

  # B A C K U P   S E R V E R S
  # Configure each backup server
  def app_setup(vm, app_file)
    # Make an app
    vm.vm.provision "file", source: "files/package.json", destination: "/home/vagrant/package.json"
    vm.vm.provision "file", source: "files/#{app_file}", destination: "/home/vagrant/app.js"
    vm.vm.provision "shell", inline: <<-SHELL
      cd /home/vagrant
      npm install
    SHELL
    vm.vm.provision "shell", inline: <<-SHELL, run: "always"
      nohup node app.js > app.log 2>&1 &      
    SHELL
    # Apply firewall rules
    vm.vm.provision "shell", inline: <<-SHELL
      sudo systemctl enable --now firewalld
      sudo firewall-cmd --permanent --add-port=3000/tcp
      sudo firewall-cmd --permanent --add-port=3001/tcp
      sudo firewall-cmd --permanent --add-port=3002/tcp
      sudo firewall-cmd --reload
    SHELL
  end

  # BACKUP 1
  config.vm.define "b1" do |b1|
    b1.vm.hostname = "backup1"
    b1.vm.network "private_network", ip: "192.168.33.11"
    b1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    app_setup(b1, "app1.js")
  end

  # BACKUP 2
  config.vm.define "b2" do |b2|
    b2.vm.hostname = "backup2"
    b2.vm.network "private_network", ip: "192.168.33.12"
    b2.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    app_setup(b2, "app2.js")
  end

  # BACKUP 3
  config.vm.define "b3" do |b3|
    b3.vm.hostname = "backup3"
    b3.vm.network "private_network", ip: "192.168.33.13"
    b3.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    app_setup(b3, "app3.js")
  end

  # B A L A N C E R
  config.vm.define "bal" do |bal|
    bal.vm.hostname = "balancer"
    bal.vm.network "private_network", ip: "192.168.33.10"
    bal.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    # Enables HTTP traffic
    bal.vm.provision "shell", inline: <<-SHELL
      sudo systemctl enable --now firewalld
      sudo firewall-cmd --permanent --add-service=http
      sudo firewall-cmd --reload
    SHELL

    # Nginx config
    bal.vm.provision "file", source: "files/nginx.conf", destination: "/home/vagrant/nginx.conf"
    bal.vm.provision "shell", inline: <<-SHELL
      sudo mv /home/vagrant/nginx.conf /etc/nginx/nginx.conf
      sudo restorecon -v /etc/nginx/nginx.conf
      sudo nginx -t && sudo systemctl restart nginx
      sudo systemctl status nginx
    SHELL
  end

end
