Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "oraclelinux/9"
    web.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json"
    web.vm.hostname = "webserver"
    web.vm.network "private_network", ip: "192.168.33.10"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "oraclelinux/9"
    db.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json"
    db.vm.hostname = "dbserver"
    db.vm.network "private_network", ip: "192.168.33.11"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

end